# Generated by Django 4.1.3 on 2022-11-30 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Salon', 'verbose_name_plural': 'Salones'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='idSalon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.salon'),
            preserve_default=False,
        ),
    ]
