# Generated by Django 4.1.3 on 2022-11-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_alumno_primary_key_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedAlum',
            fields=[
            ],
            options={
                'ordering': ['last_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.alumno',),
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'ordering': ['hora_entrada'], 'verbose_name': 'Salon', 'verbose_name_plural': 'Salones'},
        ),
    ]
